package com.dlc.electronicbalance.database;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.dlc.electronicbalance.database.WeighDatasBean;

import com.dlc.electronicbalance.database.WeighDatasBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig weighDatasBeanDaoConfig;

    private final WeighDatasBeanDao weighDatasBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        weighDatasBeanDaoConfig = daoConfigMap.get(WeighDatasBeanDao.class).clone();
        weighDatasBeanDaoConfig.initIdentityScope(type);

        weighDatasBeanDao = new WeighDatasBeanDao(weighDatasBeanDaoConfig, this);

        registerDao(WeighDatasBean.class, weighDatasBeanDao);
    }
    
    public void clear() {
        weighDatasBeanDaoConfig.clearIdentityScope();
    }

    public WeighDatasBeanDao getWeighDatasBeanDao() {
        return weighDatasBeanDao;
    }

}
